spring.application.name=final-project

# **** Variables para SEO y Redes Sociales ****
# En desarrollo local: http://localhost:5173
# En producción: ej: https://www.carlikeafriend.com
frontend.base-url=${FRONTEND_URL:http://localhost:5173}

# En desarrollo local: http://localhost:8080
# En producción: ej: https://api.carlikeafriend.com (o el mismo dominio si están juntos)
backend.base-url=${BACKEND_URL:http://localhost:8080}

# **** Configuración de Archivos ****
# Ruta donde se guardarán las imágenes
file.upload-dir=${UPLOAD_DIR:./uploads}


# **** Frontend ****
# Ruta de inicio de sesión
app.frontend.login-url=${FRONTEND_LOGIN_URL:http://localhost:5173/signin}


# **** Límites de subida ****
# Permitir subidas
spring.servlet.multipart.enabled=true

# Límite por archivo individual (Un poco más de lo que se valida en Java)
spring.servlet.multipart.max-file-size=6MB

# Límite total de la petición (Suma de todas las imágenes + JSON)
# 5 imagenes * 5MB = 25MB + margen = 30MB
spring.servlet.multipart.max-request-size=30MB


# **** Base de Datos ****
# Configuración de conexión a MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/carlikeafriend-db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# **** JPA/Hibernate ****
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# **** Seguridad ****
# Esta clave DEBE ser un string largo y aleatorio codificado en Base64.
jwt.secret.key=${JWT_SECRET}

# Tiempos de expiración configurables - Tiempo en milisegundos (3600000 = 1 hora. Recomendado para Access Token)
jwt.expiration.access-token=3600000


# **** Correo ****
# Configuración del servidor de correo (Ejemplo con Yahoo)
spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true