spring.application.name=final-project

# Ruta donde se guardarán las imágenes
file.upload-dir=G:\\app-data\\uploads

#Limita el tamaño de los archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/carlikeafriend-db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración adicional de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

